project:
  type: website

brand: _brand.yml

execute:
  enabled: false

website:
  title: "EGU26 - Short Course: Compound Events and Multi-Hazard Analytics"

  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introductions"
        menu:
          - text: "Overview of Compound Events"
            href: materials/01-intro-compound-events/index.qmd
          - text: "From Single-Hazard to Multi-Risk"
            href: materials/02-intro-multi-risk/index.qmd
      - text: "Applications"
        menu:
          - text: "Vine Copulas: Overview & Slides"
            href: materials/03-vine-copulas/index.qmd
          - text: "Notebook 1: Bivariate Copulas"
            href: materials/03-vine-copulas/bivariatecopulas.ipynb
          - text: "Notebook 2: Vine Copulas"
            href: materials/03-vine-copulas/vinecopulas.ipynb
          - text: "---"
          - text: "LLM Impact Extraction: Overview & Slides"
            href: materials/04-llm-impact-extraction/index.qmd
          - text: "Notebook: Impact Extraction"
            href: materials/04-llm-impact-extraction/notebook.ipynb

  page-footer:
    border: true
    background: light
    left: |
      [![MedEWSa](/images/logos/Logo_MedEWSa_PNG_TRASPARENT.png){height="48px" style="margin-right:1.2rem;"}](https://medewsa.eu)
      [![EU Funded](/images/logos/funded_EN/horizontal/RGB/PNG/EN_FundedbytheEU_RGB_POS.png){height="48px"}](https://ec.europa.eu)
    center: |
      [![](https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg)](https://creativecommons.org/licenses/by/4.0/)
    right: |
      This repository is funded by the European Union. Its contents are the sole responsibility of the author(s) and do not necessarily reflect the views of the European Union.

format:
  html:
    theme: [flatly, styles.scss]
    highlight-style: github # potential options include github, tango, a11y, pygments
    from: markdown+emoji
    toc: true
    toc-depth: 2
    grid:
      body-width: 1100px    # Default is usually ~900px. This widens the text column.
      margin-width: 300px   # This ensures the TOC still has enough room on the right.
