project:
  type: website

brand: _brand.yml

execute:
  enabled: false

website:
  title: "EGU26 - Short Course: Compound Events and Multi-Hazard Analytics"

  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introductions"
        menu:
          - text: "Overview of Compound Events"
            href: materials/01-intro-compound-events/index.qmd
          - text: "From Single-Hazard to Multi-Risk"
            href: materials/02-intro-multi-risk/index.qmd
      - text: "Applications"
        menu:
          - text: "Vine Copulas: Overview & Slides"
            href: materials/03-vine-copulas/index.qmd
          - text: "Jupyter notebook 1: Bivariate Copulas"
            href: materials/03-vine-copulas/bivariatecopulas.ipynb
          - text: "Jupyter notebook 2: Vine Copulas"
            href: materials/03-vine-copulas/vinecopulas.ipynb
          - text: "---"
          - text: "Extracting Climate Impacts from Text with LLMs: Overview"
            href: materials/04-llm-impact-extraction/index.qmd
          - text: "Jupyter notebook"
            href: materials/04-llm-impact-extraction/tutorial.ipynb
      - text: "About"
        href: about.qmd

  page-footer:
    border: true
    background: light
    center: |
      [![](https://img.shields.io/badge/License-CC%20BY%204.0-lightgrey.svg)](https://creativecommons.org/licenses/by/4.0/)

format:
  html:
    theme: [flatly, styles.scss]
    highlight-style: github # potential options include github, tango, a11y, pygments
    from: markdown+emoji
    toc: true
    toc-depth: 2
